server:
  port: 4242
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/delivery_api
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}